name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  cached_network_image: ^3.2.3
  hive_ce: 2.13.0
  hive_ce_flutter: ^2.3.0

  # JavaScript runtime
  flutter_js: ^0.8.7

  # WebView (Cloudflare bypass)
  flutter_inappwebview: ^6.0.0

  dio: ^5.11.0
  path_provider: ^2.1.6
  get_it: ^9.2.1
  xml: ^6.6.1
  video_player: ^2.13.0
  palette_generator: ^0.3.3+7
  flutter_riverpod: ^3.3.2
  ffi: ^2.2.0

  # Media Kit Player
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

  # Rust FFI Bindings
  rust_lib_frontend:
    path: rust_builder
  flutter_rust_bridge: 2.12.0

  # Go Torrent Streamer
  flutter_go_torrent_streamer: ^0.0.8
  package_info_plus: ^10.2.1
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/extensions/

# ----------------------------------------------------
# Flutter Launcher Icons Configuration
# ----------------------------------------------------
flutter_launcher_icons:
  android: true
  ios: false

  image_path: "assets/playstore.png"

  adaptive_icon_background: "#0F1115"
  adaptive_icon_foreground: "assets/playstore.png"

  min_sdk_android: 21
  remove_alpha_ios: true
