// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<TorrentItem>> searchAnimetosho({required String query}) =>
    RustLib.instance.api.crateApiFetchersSearchAnimetosho(query: query);

class TorrentItem {
  final String provider;
  final String title;
  final String size;
  final int seeders;
  final String age;
  final bool isVerified;
  final List<String> tags;
  final String magnetUrl;

  const TorrentItem({
    required this.provider,
    required this.title,
    required this.size,
    required this.seeders,
    required this.age,
    required this.isVerified,
    required this.tags,
    required this.magnetUrl,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      title.hashCode ^
      size.hashCode ^
      seeders.hashCode ^
      age.hashCode ^
      isVerified.hashCode ^
      tags.hashCode ^
      magnetUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentItem &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          title == other.title &&
          size == other.size &&
          seeders == other.seeders &&
          age == other.age &&
          isVerified == other.isVerified &&
          tags == other.tags &&
          magnetUrl == other.magnetUrl;
}
